Bump core and web-ui versions
cytomine/Cytomine-community-edition pull request #13
Opened 2024-01-23 13:14 UTC by bathienle

## Description

- Set the commercial version to BP2024.1
- Bump core to version bp-0.1.0
- Bump web-ui to version bp-0.1.0
- Remove duplicate keys (image and smtp)

2024-01-23 13:18 UTC, waliens requested changes

2024-01-23 13:18 UTC, waliens commented on cytomine.template
> -  smtp:
why have you removed this ?

2024-01-23 13:22 UTC, bathienle commented on cytomine.template
> -  smtp:
It is a duplicate key that appears in https://github.com/cytomine/Cytomine-community-edition/blob/main-bigpicture/cytomine.template#L34 or should I instead remove L34 ?

2024-01-24 14:37 UTC, urubens commented on cytomine.template
> -  smtp:
I saw those duplicates keys have been introduced by c42c3b47cde1cf82944ef56dead5d18e700c040b and have been removed after. In the end, all keys are there so it's ok.

2024-01-24 14:38 UTC, merged